# Домашнее Задание 1

####  Валерія Дружиніна

## NumPy

####  1. Создайте массив  с 10 случайными числами из распределения Гаусса

In [ ]:
import numpy as np
np.random.randn(10)

#### 2. Создайте следующую матрицу: https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

In [ ]:
a=np.linspace(0,1,num=101) #create
b = a.round(2) #round

skip_zero=a[1:101] #skip 0

skip_zero.reshape(10,10) #build matrix

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### 3. Создайте 2х3 матрицу с равномерно распределенными числами между 5 и 20

In [ ]:
a=np.linspace(5,20,num=6).reshape(2,3) #build matrix
a

array([[ 5.,  8., 11.],
       [14., 17., 20.]])

## Выбор

#### 1. Напишите код, в результате которого вы получите предложенный результат

In [ ]:
mat = np.arange(1,31).reshape(2,3,5)
mat

mat[:,2] # Результат 1

mat[:,1,0] #Результат 2

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [ ]:
# Результат 1, не нажимайте на эту клетку

array([[11, 12, 13, 14, 15],
       [26, 27, 28, 29, 30]])

In [ ]:
# Результат 2, не нажимайте на эту клетку

array([ 6, 21])

## Pandas

#### 1. Выведите датасет Salaries.csv в дата фрейм sal
Это данные kaggle о зарплатах сотрудников города Сан Франциско

In [ ]:
import pandas as pd
sal=pd.read_csv("Salaries.csv")
sal

#### 2. Покажите 5 первых строк датафрейма

In [ ]:
sal.head()

#### 3. Какая средняя базовая зарплата (BasePay)?

In [ ]:
mean=sal['BasePay'].mean()
mean #66325.44884050643

#### 4. Какая самая высокая зарплата за дополнителную работу OvertimePay?

In [ ]:
max=sal['OvertimePay'].max()
max #245131.88

#### 5. Какая профессия у JOSEPH DRISCOLL? (Пишите имя большими буквами)

In [ ]:
sal[sal['EmployeeName']=='PATRICK GARDNER'] #DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)

#### 6. Как зовут человека с самой большой зарплатой?

In [ ]:
max=sal['OvertimePay'].max()
sal[sal['OvertimePay']==max] #GARY JIMENEZ	

#### 7. Сколько уникальных профессий в таблице?

In [ ]:
sal['JobTitle'].unique() #2159

#### 8. Какие 5 профессий повторяются чаще всего? 

In [ ]:
sal['JobTitle'].value_counts().head() 
#Transit Operator(7036),Special Nurse(4389),Registered Nurse(3736),Public Svc Aide-Public Works(2518),Police Officer(3) 